### ISSUE TITLE
In linux 5.10.83 , creating a macvlan causes the NI device to reboot.

### ISSUE THREAD

**Issue by zhaotianWu1** [ni/linux#122]
In linux 5.10.83 , creating a macvlan causes the NI device to reboot.
Hardware: NI device x86 (run mode NI-PXIe-8861-03219D90)
Software: linux 5.10.83-rt58

The "macvlan" kernel module is loaded normally, but when the "ip link add link ens06 name ens06.01 type macvlan" command is executed, the device does not respond, does not output any commands, and the device reboots after 3 seconds.
The NI device can normally load the "macvlan" kernel module in linux 4.14.146-rt67 , and can use the "ip link add link ens06 name ens06.01 type macvlan" command to create a macvlan normally.

**Comment by chaitu236** [comment]
I haven't been able to reproduce this issue on a PXIe-8861 provisioned with `21.5` System Image, and `5.10.83-rt58` kernel with `macvlan` module added; `ip link add..` succeeded and created the link.

If you have any other kernel changes, you may want to check those. You can also try on a newer 5.10 kernel (2022Q3 System Image, `nilrt/22.5/5.10` branch in this repo) or a 5.15 kernel (2022Q2 System Image, `nilrt/23.3/5.15` branch in this repo).

**Comment by zhaotianWu1** [comment]
Thank you for your reply. The issue has been resolved. The previous macvlan. ko module was compiled separately. Afterwards, I fully compiled the source code and generated a new ko module to verify that the new ko module is working properly.
