### ISSUE TITLE
nipalk.ko lost

### ISSUE THREAD

**Issue by yangkkokk** [ni/linux#179]
5.15.113-rt64

change bzimge error

libnipalu.so failed to initialize
Verify that nipalk.ko is built and loaded.
Startup application prevented from running at startup.

**Comment by gratian** [comment]
@yangkkokk you can verify if the nipalk module is loaded by running the 'lsmod' command in a terminal (serial/ssh) and checking if nipalk is listed in the output.

It is unclear if you are seeing this error after compiling a custom kernel. If yes then make sure you've completed the steps under "Rebuilding NI out-of-tree Drivers with DKMS" section in the kernel readme here: https://github.com/ni/nilrt/blob/nilrt/master/kirkstone/docs/README.kernel.md

If you are seeing this error after a standard install on NI hardware, please use the regular NI support channels to report the issue. 'nipalk' is a out-of-tree closed source kernel module that is not maintained out of this open-source git repo.

**Comment by gratian** [comment]
@yangkkokk did the suggestions above help?

**Comment by gratian** [comment]
@yangkkokk I'm going to assume the suggestions provided worked and I'm going to close this issue. If you have additional issues/comments feel free to re-open.
